parameters:
    # nothing to declare
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ecosystem\ActivityLogDoctrineBundle\Listener\ActivityLogDoctrineListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }
